skills: 
  tank:
    items:
     - Broadsword
     - Splash Damage Resistance
     - Defence Artifact
     - Diamond Helmet
     - Diamond Chestplate
     - Diamond Leggings
     - Diamond Boots
  healer:
    items:
      - Healers Trusty Dagger
      - Splash Regeneration
      - Splash Healing
      - Iron Helmet
      - Iron Chestplate
      - Iron Leggings
      - Iron Boots
  dps:
    items:
      - Long Bow
      - Splash DPS
      - Splash Strength
      - Leather Helmet
      - Leather Chestplate
      - Leather Leggings
      - Leather Boots
  bard:
    items:
      - Boarding Axe
      - Splash Speed
      - Splash Fire Resistance
      - Chain Helmet
      - Chain Chestplate
      - Chain Leggings
      - Chain Boots
Items:
  Splash Regeneration:
    Location: spawn
    Type: POTION
    Lore: Regeneration Potion to increase health.
    Cost: 10
    Buffs:
    Debuffs:
    Duration: 10
    Potency: 2
    Potion Icon: REGEN
    Splash: true
    Qty: 2
    Cooldown: 20
    Potion Type: REGENERATION
    Base Class: Healer
    Class Level Requirement: 5
  Splash DPS:
    Location: spawn
    Type: POTION
    Lore: Potion of damage. Be careful not to friendly fire!
    Cost: 10
    Buffs:
    Debuffs:
    Duration: 10
    Potency: 2
    Potion Icon: INSTANT_DAMAGE 
    Splash: true
    Qty: 2
    Cooldown: 20
    Potion Type: HARM
    Base Class: DPS
    Class Level Requirement: 5
  Splash Strength:
    Location: spawn
    Type: POTION
    Lore: Deal extra damage!
    Cost: 10
    Buffs:
    Debuffs:
    Duration: 20
    Potency: 2
    Potion Icon: STRENGTH  
    Splash: false
    Qty: 2
    Cooldown: 20
    Potion Type: INCREASE_DAMAGE
    Base Class: DPS
    Class Level Requirement: 5
  Splash Speed:
    Location: spawn
    Type: POTION
    Lore: An old, damaged helmet, It'll do though.
    Cost: 10
    Buffs:
    Debuffs:
    Duration: 10
    Potency: 2
    Potion Icon: SPEED 
    Splash: false
    Qty: 3
    Cooldown: 20
    Potion Type: SPEED
    Base Class: Bard
    Class Level Requirement: 5
  Splash Healing:
    Location: spawn
    Type: POTION
    Lore: An old, damaged helmet, It'll do though.
    Cost: 10
    Buffs:
    Debuffs:
    Duration: 10
    Potency: 2
    Potion Icon: INSTANT_HEAL 
    Splash: true
    Qty: 3
    Cooldown: 20
    Potion Type: HEAL
    Base Class: Healer
    Class Level Requirement: 5
  Splash Fire Resistance:
    Location: spawn
    Type: POTION
    Lore: An old, damaged helmet, It'll do though.
    Cost: 10
    Buffs:
    Debuffs:
    Duration: 10
    Potency: 2
    Potion Icon: FIRE_RESISTANCE 
    Splash: true
    Qty: 3
    Cooldown: 20
    Potion Type: FIRE_RESISTANCE
    Base Class: Bard
    Class Level Requirement: 5
  Splash Damage Resistance:
    Location: spawn
    Type: POTION
    Lore: An old, damaged helmet, It'll do though.
    Cost: 10
    Buffs:
    Debuffs:
    Duration: 10
    Potency: 2
    Potion Icon: JUMP
    Splash: true
    Qty: 3
    Cooldown: 20
    Potion Type: DAMAGE_RESISTANCE
    Base Class: Tank
    Class Level Requirement: 5
  Leather Helmet:
    Location: spawn
    Type: LEATHER_HELMET
    Lore: An old, damaged helmet, It'll do though.
    Enchanted: false
    Cost: 10
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: DPS
    Class Level Requirement: 5
  Leather Chestplate:
    Location: spawn
    Type: LEATHER_CHESTPLATE
    Lore: An old, damaged chestpiece. It'll do though.
    Enchanted: false
    Cost: 25
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: DPS
    Class Level Requirement: 5
  Leather Leggings:
    Location: spawn
    Type: LEATHER_LEGGINGS
    Lore: An old, damaged set of legs. It'll do though.
    Enchanted: false
    Cost: 15
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: DPS
    Class Level Requirement: 5
  Leather Boots:
    Location: spawn
    Type: LEATHER_BOOTS
    Lore: An old, damaged set of boots. It'll do though.
    Enchanted: false
    Cost: 10
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: DPS
    Class Level Requirement: 5
  Iron Helmet:
    Location: spawn
    Type: IRON_HELMET
    Lore: An old, damaged helmet, It'll do though.
    Enchanted: false
    Cost: 10 
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: Healer
    Class Level Requirement: 5
  Iron Chestplate:
    Location: spawn
    Type: IRON_CHESTPLATE
    Lore: An old, damaged chestpiece. It'll do though.
    Enchanted: false
    Cost: 25
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: Healer
    Class Level Requirement: 5
  Iron Leggings:
    Location: spawn
    Type: IRON_LEGGINGS
    Lore: An old, damaged set of legs. It'll do though.
    Enchanted: false
    Cost: 15
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: Healer
    Class Level Requirement: 5
  Iron Boots:
    Location: spawn
    Type: IRON_BOOTS
    Lore: An old, damaged set of boots. It'll do though.
    Enchanted: false
    Cost: 10
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: Healer
    Class Level Requirement: 5
  Diamond Helmet:
    Location: spawn
    Type: DIAMOND_HELMET
    Lore: An old, damaged helmet, It'll do though.
    Enchanted: false
    Cost: 10 
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: Tank
    Class Level Requirement: 5
  Diamond Chestplate:
    Location: spawn
    Type: DIAMOND_CHESTPLATE
    Lore: An old, damaged chestpiece. It'll do though.
    Enchanted: false
    Cost: 25
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: Tank
    Class Level Requirement: 5
  Diamond Leggings:
    Location: spawn
    Type: DIAMOND_LEGGINGS
    Lore: An old, damaged set of legs. It'll do though.
    Enchanted: false
    Cost: 15
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: Tank
    Class Level Requirement: 5
  Diamond Boots:
    Location: spawn
    Type: DIAMOND_BOOTS
    Lore: An old, damaged set of boots. It'll do though.
    Enchanted: false
    Cost: 10
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: Tank
    Class Level Requirement: 5
  Chain Helmet:
    Location: spawn
    Type: CHAINMAIL_HELMET
    Lore: An old, damaged helmet, It'll do though.
    Enchanted: false
    Cost: 10 
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: Bard
    Class Level Requirement: 5
  Chain Chestplate:
    Location: spawn
    Type: CHAINMAIL_CHESTPLATE
    Lore: An old, damaged chestpiece. It'll do though.
    Enchanted: false
    Cost: 25
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: Bard
    Class Level Requirement: 5
  Chain Leggings:
    Location: spawn
    Type: CHAINMAIL_LEGGINGS
    Lore: 
    Enchanted: false
    Cost: 15
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: Bard
    Class Level Requirement: 5
  Chain Boots:
    Location: spawn
    Type: CHAINMAIL_BOOTS
    Lore: 
    Enchanted: false
    Cost: 15
    Buffs:
    Debuffs:
    Protection: 3
    Base Class: Bard
    Class Level Requirement: 5
  Boarding Axe:
    Location: spawn
    Type: IRON_AXE
    Lore: A brutal axe once used with deadly efficiency by sailors
    Enchanted: true
    Cost: 125
    Buffs:
    Debuffs:
      - Slowness1
    Damage: 5
    Base Class: Bard
    Class Level Requirement: 5
  Klamath Dagger:
    Location: spawn
    Type: STONE_SWORD
    Lore: A foreign dagger made of stone. 
    Enchanted: true
    Cost: 300
    Buffs:
     - poison1
    Debuffs:
    Damage: 5
    Base Class: DPS
    Class Level Requirement: 5
  Klamath Scimitar:
    Location: spawn
    Type: STONE_SWORD
    Lore: A scimitar made of stone.
    Enchanted: true
    Cost: 450
    Buffs:
     - poison1
    Debuffs:
    Damage: 7
    Base Class: DPS
    Class Level Requirement: 5
  Longsword:
    Location: spawn
    Type: IRON_SWORD
    Lore: A long blade of shining steel.
    Enchanted: true
    Cost: 500
    Buffs:
    Debuffs:
     - Slowness1
     - MiningFatigue
    Damage: 9
    Base Class: Tank
    Class Level Requirement: 5
  Broadsword:
    Location: spawn
    Type: IRON_SWORD
    Lore: A brutal thick blade thats extremely heavy.
    Enchanted: true
    Cost: 650
    Buffs:
    Debuffs:
     - Slowness2
     - MiningFatigue
    Damage: 12
    Base Class: Tank
    Class Level Requirement: 5
  Claymore:
    Type: IRON_SWORD
    Location: spawn
    Lore: This is a rusty iron sword crafted by a young blacksmith apprentice. It doesn't do much damage but you can tell the poor kid put hit heart and soul into it
    Enchanted: false
    Cost: 20
    Buffs:
      - Bleed1
      - Stun1
      - Blind1
    Debuffs:
      - Slowness1
      - MiningFatigue
    Base Class: DPS
    Class Level Requirement: 5
  Healers Trusty Dagger:
    Type: IRON_SWORD
    Location: spawn
    Lore: Allows the shanker to make a clean getaway
    Enchanted: false
    Cost: 20
    Buffs:
    - Evade1
    Debuffs:
    Base Class: Healer
    Class Level Requirement: 5
  Chameleon Staff:
    Type: BLAZE_ROD
    Location: other
    Lore: This spooky staff grants permenent cloaking when holding it
    Enchanted: false
    Cost: 20
    Buffs:
      - Cloak
    Debuffs:
    Base Class: Bard
    Class Level Requirement: 5
  Swiehandler:
    Type: IRON_SWORD
    Location: other
    Lore: A 2 meter long sword that weighs more at least 100kg. Why would anybody consider wielding this?
    Enchanted: false
    Cost: 40
    Buffs:
      - Fatigue1
      - Bleed1
      - Fatigue2
    Debuffs:
      - Slowness1
    Base Class: DPS
    Class Level Requirement: 5
  Hunting Bow:
    Type: BOW
    Location: other
    Lore: A pesky little hunting bow. Duration use burdens the archer with lasting blisters
    Enchanted: false
    Cost: 15
    Buffs:
      - Bleed1
      - Blind1
    Debuffs:
      - Slowness1
    Base Class: DPS
    Class Level Requirement: 5
  Long Bow:
    Type: BOW
    Location: spawn
    Lore: The great long bow that Sir Johnathan Weathersteed rode into battle with.
    Enchanted: false
    Cost: 100
    Buffs:
      - Bleed1
      - Fatigue2
    Debuffs:
      - Aim1
    Base Class: DPS
    Damage: 6
    Class Level Requirement: 5
  Calebs Bow:
    Type: BOW
    Location: other
    Lore: The great long bow that Sir Johnathan Weathersteed rode into battle with.
    Enchanted: false
    Cost: 100
    Buffs:
      - Bleed1
      - Fatigue2
      - poison1
    Debuffs:
    damage: 5
    Base Class: DPS
    Class Level Requirement: 5
  Defence Artifact:
    Type: BLAZE_POWDER
    Location: other
    Lore: Equiping this artifact grants bonus health
    Enchanted: false
    Cost: 100
    Buffs:
      - HealthBoost1
    Debuffs:
    Base Class: Tank
    Class Level Requirement: 5
Buffs:
  Bleed1:
    Rate: 0.5
    Duration: 3
    Interval: 20
    Intensity: 1
    Type: damageOverTime
    Target: opponent
    Trigger: hit
  Fatigue1:
    Rate: 0
    Duration: 3
    Interval: 20
    Intensity: 1
    Type: slowness
    Target: opponent
    Trigger: hit
  Fatigue2:
    Rate: 0
    Duration: 5
    Interval: 20
    Intensity: 2
    Type: slowness
    Target: opponent
    Trigger: hit
  Stun1:
    Rate: 0
    Duration: 10
    Interval: 20
    Intensity: 3
    Type: nausea
    Target: opponent
    Trigger: hit
  Blind1:
    Rate: 0
    Duration: 10
    Interval: 20
    Intensity: 3
    Type: blind
    Target: opponent
    Trigger: hit
  poison1:
    Rate: 0
    Duration: 5
    Interval: 20
    Intensity: 1
    Type: poison
    Target: opponent
    Trigger: hit
  Cloak:
    Rate: 0
    Duration: 0
    Interval: 0
    Intensity: 0
    Type: chameleon
    Target: player
    Trigger: have
  Evade1:
    Rate: 0
    Duration: 2
    Interval: 20
    Intensity: 2
    Type: speed
    Target: player
    Trigger: hit
  HealthBoost1:
    Rate: 0
    Duration: 0
    Interval: 20
    Intensity: 10
    Type: healthboost
    Target: player
    Trigger: have
Debuffs:
  Slowness1:
    Rate: 0
    Duration: 0
    Interval: 20
    Intensity: 1
    Type: slowness
    Target: player
    Trigger: have
  Slowness2:
    Rate: 0
    Duration: 0
    Interval: 20
    Intensity: 2
    Type: slowness
    Target: player
    Trigger: have
  Slowness3:
    Rate: 0
    Duration: 0
    Interval: 20
    Intensity: 3
    Type: slowness
    Target: player
    Trigger: have
  Aim1:
    Rate: 0
    Duration: 0
    Interval: 20
    Intensity: 3
    Type: slowness
    Target: player
    Trigger: hold
  MiningFatigue:
    Rate: 0
    Duration: 0
    Interval: 20
    Intensity: 7
    Type: miningfatigue
    Target: player
    Trigger: hold
Locations:
  spawn:
    testoption: false
  other:
    testoption: false
  Renford:
    testoption: false
  Erzquarry:
    testoption: false
  Torvale:
    testoption: false
  Luxemdale:
    testoption: false
  Amplequay:
    testoption: false
  
  
    