skills: 
  Tank:
    items:
     - Longsword
     - Broadsword
     - Claymore
     - Diamond Helmet
     - Diamond Chestplate
     - Diamond Leggings
     - Diamond Boots
  Healer:
    items:
      - Leather Helmet
      - Leather Chestplate
      - Leather Leggings
      - Leather Boots
      - Klamath Dagger
  DPS:
    items:
      - Klamath Scimitar
      - Iron Helmet
      - Iron Chestplate
      - Iron Leggings
      - Iron Boots
  Bard:
    items:
      - Boarding Axe
      - Chain Helmet
      - Chain Chestplate
      - Chain Leggings
      - Chain Boots
Items:
  Leather Helmet:
    Location: spawn
    Type: LEATHER_HELMET
    Lore: An old, damaged helmet, It'll do though.
    Enchanted: false
    Cost: 10
    Buffs:
    Debuffs:
    Protection: 3
  Leather Body:
    Location: spawn
    Type: LEATHER_CHESTPLATE
    Lore: An old, damaged chestpiece. It'll do though.
    Enchanted: false
    Cost: 25
    Buffs:
    Debuffs:
    Protection: 3
  Leather Legs:
    Location: spawn
    Type: LEATHER_LEGGINGS
    Lore: An old, damaged set of legs. It'll do though.
    Enchanted: false
    Cost: 15
    Buffs:
    Debuffs:
    Protection: 3
  Leather Boots:
    Location: spawn
    Type: LEATHER_BOOTS
    Lore: An old, damaged set of boots. It'll do though.
    Enchanted: false
    Cost: 10
    Buffs:
    Debuffs:
    Protection: 3
  Iron Helmet:
    Location: spawn
    Type: IRON_HELMET
    Lore: An old, damaged helmet, It'll do though.
    Enchanted: false
    Cost: 10 
    Buffs:
    Debuffs:
    Protection: 3
  Iron Body:
    Location: spawn
    Type: IRON_CHESTPLATE
    Lore: An old, damaged chestpiece. It'll do though.
    Enchanted: false
    Cost: 25
    Buffs:
    Debuffs:
    Protection: 3
  Iron Legs:
    Location: spawn
    Type: IRON_LEGGINGS
    Lore: An old, damaged set of legs. It'll do though.
    Enchanted: false
    Cost: 15
    Buffs:
    Debuffs:
    Protection: 3
  Iron Boots:
    Location: spawn
    Type: IRON_BOOTS
    Lore: An old, damaged set of boots. It'll do though.
    Enchanted: false
    Cost: 10
    Buffs:
    Debuffs:
    Protection: 3
  Diamond Helmet:
    Location: spawn
    Type: DIAMOND_HELMET
    Lore: An old, damaged helmet, It'll do though.
    Enchanted: false
    Cost: 10 
    Buffs:
    Debuffs:
    Protection: 3
  Diamond Body:
    Location: spawn
    Type: DIAMOND_CHESTPLATE
    Lore: An old, damaged chestpiece. It'll do though.
    Enchanted: false
    Cost: 25
    Buffs:
    Debuffs:
    Protection: 3
  Diamond Legs:
    Location: spawn
    Type: DIAMOND_LEGGINGS
    Lore: An old, damaged set of legs. It'll do though.
    Enchanted: false
    Cost: 15
    Buffs:
    Debuffs:
    Protection: 3
  Diamond Boots:
    Location: spawn
    Type: DIAMOND_BOOTS
    Lore: An old, damaged set of boots. It'll do though.
    Enchanted: false
    Cost: 10
    Buffs:
    Debuffs:
    Protection: 3
  Chain Helmet:
    Location: spawn
    Type: CHAINMAIL_HELMET
    Lore: An old, damaged helmet, It'll do though.
    Enchanted: false
    Cost: 10 
    Buffs:
    Debuffs:
    Protection: 3
  Chain Body:
    Location: spawn
    Type: CHAINMAIL_CHESTPLATE
    Lore: An old, damaged chestpiece. It'll do though.
    Enchanted: false
    Cost: 25
    Buffs:
    Debuffs:
    Protection: 3
  Chain Legs:
    Location: spawn
    Type: CHAINMAIL_LEGGINGS
    Lore: 
    Enchanted: false
    Cost: 15
    Buffs:
    Debuffs:
    Protection: 3
  Boarding Axe:
    Location: spawn
    Type: IRON_AXE
    Lore: A brutal axe once used with deadly efficiency by sailors
    Enchanted: true
    Cost: 125
    Buffs:
    Debuffs:
      - Slowness1
    Damage: 5
  Klamath Dagger:
    Location: spawn
    Type: STONE_SWORD
    Lore: A foreign dagger made of stone. 
    Enchanted: true
    Cost: 300
    Buffs:
     - poison1
    Debuffs:
    Damage: 5
  Klamath Scimitar:
    Location: spawn
    Type: STONE_SWORD
    Lore: A scimitar made of stone.
    Enchanted: true
    Cost: 450
    Buffs:
     - poison1
    Debuffs:
    Damage: 7
  Longsword:
    Location: spawn
    Type: IRON_SWORD
    Lore: A long blade of shining steel.
    Enchanted: true
    Cost: 500
    Buffs:
    Debuffs:
     - Slowness1
    Damage: 9
  Broadsword:
    Location: spawn
    Type: IRON_SWORD
    Lore: A brutal thick blade thats extremely heavy.
    Enchanted: true
    Cost: 650
    Buffs:
    Debuffs:
     - Slowness2
    Damage: 12
  Claymore:
    Location: spawn
    Type: IRON_SWORD
    Location:
    Lore: This is a rusty iron sword crafted by a young blacksmith apprentice. It doesn't do much damage but you can tell the poor kid put hit heart and soul into it
    Enchanted: false
    Cost: 20
    Buffs:
      - Bleed1
      - Stun1
      - Blind1
    Debuffs:
      - Slowness1
  Chameleon Staff:
    Type: BLAZE_ROD
    Location:
    Lore: This spooky staff grants permenent cloaking when holding it
    Enchanted: false
    Cost: 20
    Buffs:
      - Cloak
    Debuffs:
      - Slowness3
  Swiehandler:
    Type: IRON_SWORD
    Location:
    Lore: A 2 meter long sword that weighs more at least 100kg. Why would anybody consider wielding this?
    Enchanted: false
    Cost: 40
    Buffs:
      - Fatigue1
      - Bleed1
      - Fatigue2
    Debuffs:
      - Slowness1
  Hunting Bow:
    Type: BOW
    Location:
    Lore: A pesky little hunting bow. Extended use burdens the archer with lasting blisters
    Enchanted: false
    Cost: 15
    Buffs:
      - Bleed1
      - Blind1
    Debuffs:
      - Slowness1
  Long Bow:
    Type: BOW
    Location:
    Lore: The great long bow that Sir Johnathan Weathersteed rode into battle with.
    Enchanted: false
    Cost: 100
    Buffs:
      - Bleed1
      - Fatigue2
    Debuffs:
      - Slowness1
Buffs:
  Bleed1:
    Rate: 0.5
    Duration: 3000
    Interval: 20
    Intensity: 1
    Type: damageOverTime
    Target: opponent
    Trigger: hit
  Fatigue1:
    Rate: 0
    Duration: 3000
    Interval: 20
    Intensity: 1
    Type: slowness
    Target: opponent
    Trigger: hit
  Fatigue2:
    Rate: 0
    Duration: 5000
    Interval: 20
    Intensity: 2
    Type: slowness
    Target: opponent
    Trigger: hit
  Stun1:
    Rate: 0
    Duration: 10000
    Interval: 20
    Intensity: 3
    Type: nausea
    Target: opponent
    Trigger: hit
  Blind1:
    Rate: 0
    Duration: 10000
    Interval: 20
    Intensity: 3
    Type: blind
    Target: opponent
    Trigger: hit
  poison1:
    Rate: 0
    Duration: 5000
    Interval: 20
    Intensity: 1
    Type: poison
    Target: opponent
    Trigger: hit
  Cloak:
    Rate: 0
    Duration: 0
    Interval: 0
    Intensity: 0
    Type: chameleon
    Target: player
    Trigger: hold
Debuffs:
  Slowness1:
    Rate: 0
    Duration: 0
    Interval: 20
    Intensity: 1
    Type: slowness
    Target: player
    Trigger: hold
  Slowness2:
    Rate: 0
    Duration: 0
    Interval: 20
    Intensity: 2
    Type: slowness
    Target: player
    Trigger: hold
  Slowness3:
    Rate: 0
    Duration: 0
    Interval: 20
    Intensity: 3
    Type: slowness
    Target: player
    Trigger: hold
Locations:
  spawn:
    testoption: false
  Blithe-water:
    testoption: false
  Renford:
    testoption: false
  Erzquarry:
    testoption: false
  Torvale:
    testoption: false
  Luxemdale:
    testoption: false
  Amplequay:
    testoption: false
  
  
    